#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-bundle-validation
    image: quay.io/operator-framework/scorecard-test:v1.7.1
    labels:
      suite: olm
      test: olm-bundle-validation-test
- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-crds-have-validation
    image: quay.io/operator-framework/scorecard-test:v1.7.1
    labels:
      suite: olm
      test: olm-crds-have-validation-test
## Test was disabled. Related issue is: https://github.com/operator-framework/operator-sdk/issues/5254
# - op: add
#   path: /stages/0/tests/-
#   value:
#     entrypoint:
#     - scorecard-test
#     - olm-crds-have-resources
#     image: quay.io/operator-framework/scorecard-test:v1.7.1
#     labels:
#       suite: olm
#       test: olm-crds-have-resources-test
- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-spec-descriptors
    image: quay.io/operator-framework/scorecard-test:v1.7.1
    labels:
      suite: olm
      test: olm-spec-descriptors-test
## Test was disabled. Related issue is: https://github.com/operator-framework/operator-sdk/issues/5253
# - op: add
#   path: /stages/0/tests/-
#   value:
#     entrypoint:
#     - scorecard-test
#     - olm-status-descriptors
#     image: quay.io/operator-framework/scorecard-test:v1.7.1
#     labels:
#       suite: olm
#       test: olm-status-descriptors-test
