channels:
- currentCSV: eclipse-che-preview-openshift.v9.9.9-nightly.1599555246
  name: nightly
- currentCSV: eclipse-che-preview-openshift.v7.18.0
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-openshift
