channels:
- currentCSV: eclipse-che-preview-openshift.v9.9.9-nightly.1589556013
  name: nightly
- currentCSV: eclipse-che-preview-openshift.v7.12.2
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-openshift
