channels:
- currentCSV: eclipse-che-preview-openshift.v9.9.9-nightly.1596644591
  name: nightly
- currentCSV: eclipse-che-preview-openshift.v7.17.0
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-openshift
