packageName: eclipse-che-preview-openshift
channels:
- name: stable
  currentCSV: eclipse-che-preview-openshift.v7.0.0
- name: nightly
  currentCSV: eclipse-che-preview-openshift.v9.9.9-nightly.1564753341
defaultChannel: stable
