channels:
- currentCSV: eclipse-che-preview-openshift.v9.9.9-nightly.1567437269
  name: nightly
- currentCSV: eclipse-che-preview-openshift.v7.1.0
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-openshift
