channels:
- currentCSV: eclipse-che-preview-openshift.v9.9.9-nightly.1595010735
  name: nightly
- currentCSV: eclipse-che-preview-openshift.v7.16.1
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-openshift
