channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1592401578
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.14.2
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
