channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1578737756
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.6.0
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
