channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1582546871
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.8.0
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
