channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1593691637
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.15.1
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
