channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1586239457
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.10.0
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
