channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1591794793
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.14.1
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
