channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1588832683
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.12.2
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
