channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1598450051
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.18.1
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
