#
#  Copyright (c) 2012-2019 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-operator
  template:
    metadata:
      labels:
        app: che-operator
    spec:
      containers:
        - name: che-operator
          image: aandrienko/che-operator:imageTagIssue
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - /usr/local/bin/che-operator
          imagePullPolicy: Always
#          TODO: to be uncommented when issue
#          https://github.com/operator-framework/operator-sdk/issues/1234
#          is fixed
#          readinessProbe:
#            exec:
#              command:
#                - stat
#                - /tmp/operator-sdk-ready
#            initialDelaySeconds: 4
#            periodSeconds: 10
#            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-operator"
            - name: DEFAULT_CHE_SERVER_IMAGE_REPO
              value: "quay.io/eclipse/che-server"
            - name: DEFAULT_CHE_SERVER_IMAGE_TAG
              value: "7.8.0"
            - name: DEFAULT_PLUGIN_REGISTRY_IMAGE
              value: "quay.io/eclipse/che-plugin-registry:7.8.0"
            - name: DEFAULT_DEVFILE_REGISTRY_IMAGE
              value: "quay.io/eclipse/che-devfile-registry:7.8.0"
            - name: "DEFAULT_PVC_JOBS_IMAGE"
              value: "registry.access.redhat.com/ubi8-minimal:8.0-213"
            - name: "DEFAULT_POSTGRES_IMAGE"
              value: "centos/postgresql-96-centos7:9.6"
            - name: "DEFAULT_KEYCLOAK_IMAGE"
              value: "quay.io/eclipse/che-keycloak:7.8.0"
            - name: "DEFAULT_CHE_WORKSPACE_PLUGIN_BROKER_METADATA_IMAGE"
              value: "quay.io/crw/pluginbroker-metadata-rhel8:2.1"
            - name: "DEFAULT_CHE_WORKSPACE_PLUGIN_BROKER_ARTIFACTS_IMAGE"
              value: "quay.io/crw/pluginbroker-artifacts-rhel8:2.1"
            - name: "DEFAULT_CHE_SERVER_SECURE_EXPOSER_JWT_PROXY_IMAGE"
              value: "quay.io/crw/jwtproxy-rhel8:2.1"
      restartPolicy: Always
      serviceAccountName: che-operator
      terminationGracePeriodSeconds: 5
