#
#  Copyright (c) 2012-2019 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: che-operator
  template:
    metadata:
      labels:
        name: che-operator
    spec:
      serviceAccountName: che-operator
      containers:
        - name: che-operator
          image: che/operator
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - che-operator
          imagePullPolicy: IfNotPresent
#          TODO: to be uncommented when issue
#          https://github.com/operator-framework/operator-sdk/issues/1234
#          is fixed
#          readinessProbe:
#            exec:
#              command:
#                - stat
#                - /tmp/operator-sdk-ready
#            initialDelaySeconds: 4
#            periodSeconds: 10
#            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-operator"
            - name: CHE_VERSION
              value: "2.1"
            - name: IMAGE_default_che_server
              value: registry.redhat.io/codeready-workspaces/server-rhel8:2.1
            - name: IMAGE_default_plugin_registry
              value: registry.redhat.io/codeready-workspaces/pluginregistry-rhel8:2.1
            - name: IMAGE_default_devfile_registry
              value: registry.redhat.io/codeready-workspaces/devfileregistry-rhel8:2.1
            - name: IMAGE_default_pvc_jobs
              value: registry.access.redhat.com/ubi8-minimal:8.1-398
            - name: IMAGE_default_postgres
              value: registry.redhat.io/rhscl/postgresql-96-rhel7:1-47
            - name: IMAGE_default_keycloak
              value: registry.redhat.io/redhat-sso-7/sso73-openshift:1.0-15
            - name: IMAGE_default_che_workspace_plugin_broker_metadata
              value: registry.redhat.io/codeready-workspaces/pluginbroker-metadata-rhel8:2.1
            - name: IMAGE_default_che_workspace_plugin_broker_artifacts
              value: registry.redhat.io/codeready-workspaces/pluginbroker-artifacts-rhel8:2.1
            - name: IMAGE_default_che_server_secure_exposer_jwt_proxy_image
              value: registry.redhat.io/codeready-workspaces/jwtproxy-rhel8:2.1
