#
# Copyright (c) 2012-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

apiVersion: org.eclipse.che/v1
kind: CheBackupServerConfiguration
metadata:
  name: eclipse-che-backup-server-configuration
spec:
  # Contains backup server configuration.
  # Only one configuration is allowed.
  # Here different kinds are given as examples, but configuring several subsection will cause an error.
  # rest:
  #   hostname: rest-host.net
  #   repositoryPath: che
  #   repositoryPasswordSecretRef: secret-name
  # sftp:
  #   hostname: sftp-host.net
  #   username: user
  #   port: 2222
  #   sshKeySecretRef: backup-server-ssh-key-secret
  #   repositoryPath: che-backups
  #   repositoryPasswordSecretRef: secret-name
  awss3:
    awsAccessKeySecretRef: minio-credentials-secret
    hostname: minio.mydomain.net
    port: 9000
    protocol: http
    # Bucket should be pre-created
    repositoryPath: che-backups-bucket
    repositoryPasswordSecretRef: secret-name
