#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation

name: Testing latest changes
on: pull_request
jobs:
  minishift-e2e:
    name: Minishift
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    # All docker operations should be done in this step
    - name: Build operator image
      run: |
        export OPERATOR_IMAGE=quay.io/eclipse/che-operator:test

        brew install docker-machine docker
        docker-machine create --driver virtualbox default
        eval "$(docker-machine env default)"

        docker build -t "${OPERATOR_IMAGE}" -f Dockerfile . && docker save "${OPERATOR_IMAGE}" > operator.tar

        docker-machine stop
    - name: Install and start minishift OCP 3.11 cluster
      run: |
        brew cask install minishift
        export MINISHIFT_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
        minishift start --memory=5500 --vm-driver=virtualbox
    - name: Install chectl
      run: bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
    - name: Generate minishift certificates
      run: /bin/bash .github/action_scripts/minishift_cert_gen.sh
    - name: Update minishift deprecated certificates and run e2e
      run: |
        set -x
        export OPERATOR_IMAGE=quay.io/eclipse/che-operator:test
        export NAMESPACE="che"
        eval $(minishift oc-env)
        eval $(minishift docker-env) && docker load -i operator.tar && rm operator.tar

        /bin/bash .ci/cico_minishift_nightly.sh
    - uses: actions/upload-artifact@v2
      with:
        name: minishift-che-nightly-artifacts
        path: /tmp/artifacts-che
