#
#  Copyright (c) 2021 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#

name: Check nightly OLM bundle version
on: pull_request
jobs:
  check-bundle-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install yq
      run: sudo pip install yq
    - name: Check nightly OLM bundle version
      run: >-
        go version &&
        export GOROOT=/opt/hostedtoolcache/go/1.15.10/x64/ &&
        ${GITHUB_WORKSPACE}/.github/bin/check-nightly-olm-bundle-version.sh
