#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
name: Che Operator e2e tests
on: pull_request
jobs:
  minishift-e2e:
    name: Minishift
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build operator image
      run: |
        export OPERATOR_IMAGE=quay.io/eclipse/che-operator:test

        brew install docker-machine docker
        docker-machine --github-api-token="${{ secrets.GITHUB_TOKEN }}" create --driver virtualbox default
        eval "$(docker-machine env default)"
        docker build -t "${OPERATOR_IMAGE}" -f Dockerfile . && docker save "${OPERATOR_IMAGE}" > operator.tar
        sed -i'.bak' -e "s|quay.io\/eclipse\/che-operator:nightly|$OPERATOR_IMAGE|" deploy/operator-local.yaml

        docker-machine stop
    - name: Install and start minishift OCP 3.11 cluster
      run: |
        brew cask install minishift
        export MINISHIFT_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
        minishift start --memory=5500 --vm-driver=virtualbox
    - name: Generate minishift certificates
      run: /bin/bash .github/action_scripts/minishift_cert_gen.sh
    - name: Update minishift deprecated certificates and run e2e
      run: |
        eval $(minishift oc-env)
        eval $(minishift docker-env) && docker load -i operator.tar && rm operator.tar

        # Run E2E tests
        cat deploy/operator-local.yaml

        oc apply -f deploy/crds/org_v1_che_crd.yaml
        go mod tidy
        go run e2e/*.go

        oc get events -n che
    - uses: actions/upload-artifact@v2
      with:
        name: minishift-e2e-artifacts
        path: /tmp/artifacts-che
