#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Minikube
on: pull_request
jobs:
  minikube-gateway:
    name: Testing latest changes (single-host/gateway)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1

    - name: Install yq and pysemver
      run: |
        pip install operator-courier==2.1.7
        sudo pip install yq pysemver;
        echo "[INFO] pysemver version:"
        pysemver --version;
        echo "[INFO] yq version:"
        yq --version;
    - name: Provision Minikube cluster
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/v1.21.0/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --memory=6000mb
    - name: Enable minikube addons
      run: |
        minikube addons enable ingress
        # Enable registry and portfward to push images to registry
        /bin/bash olm/minikube-registry-addon.sh &
    - name: Install chectl
      run: bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next
    - name: Run tests
      run: /bin/bash .github/bin/minikube/test-operator-singlehost-gateway.sh
    # Run this step even the previous step fail to upload artifacts to GH
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minikube-single-host-gateway-artifacts
        path: /tmp/artifacts-che
  minikube-native:
    name: Testing latest changes (single-host/native)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install yq and pysemver
      run: sudo pip install yq pysemver
    - name: Provision Minikube cluster
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/v1.21.0/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --memory=6000mb
    - name: Enable minikube addons
      run: |
        minikube addons enable ingress
        # Enable registry and portfward to push images to registry
        /bin/bash olm/minikube-registry-addon.sh &
    - name: Install chectl
      run: bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
    - name: Run tests
      run: /bin/bash .github/bin/minikube/test-operator-singlehost-native.sh
    # Run this step even the previous step fail to upload artifacts to GH
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minikube-single-host-native-artifacts
        path: /tmp/artifacts-che
