#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#

name: Minikube
on:
  pull_request:
    branches:
      - master
jobs:
  minikube:
    name: Test Eclipse Che update from stable to nightly
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install yq
      run: sudo pip install yq
    - name: Provision Minikube cluster
      run: |
        minikube start --memory=6000mb
    - name: Enable minikube addons
      run: |
        minikube addons enable ingress
        minikube addons enable olm

        # Enable registry and portfward to push images to registry
        /bin/bash olm/minikube-registry-addon.sh &
    - name: Install chectl
      run: bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=stable
    - name: Tests
      run: /bin/bash .github/bin/minikube/test-operator-update.sh
      env:
        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
    # Run this step even the previous step fail
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minikube-updates-artifacts
        path: /tmp/artifacts-che
